name: calculator
description: "Calculator Application with Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  iconsax: ^0.0.8

  # Utilities
  url_launcher: ^6.1.12
  intl: ^0.18.1

  # State Management
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  # - - - - - -  LOCAL ASSETS - - - - - - #
  # assets:
  #   - assets/logos/
  
  # - - - - - -  LOCAL FONTS - - - - - - #
  fonts:
    - family: reem
      fonts:
        - asset: assets/fonts/Reem.ttf
          weight: 500
